apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    &a1
    sealedsecrets.bitnami.com/cluster-wide: "true"
  name: app-env
  namespace: archifiltre-statistics
spec:
  encryptedData:
    MATOMO_TOKEN: AgCktQL5i2L/1siHCFxU+Hll3FYUgc1gmepwkNBZITcJF8cQ7tL/K8GdBwWDq0+exvGFF3ItHd9lMban2fPitlkzXSgw8T0sBQlhzGE9+cSClrLkY+Ohh5lOOgXcejVVMcUmazmKVFBZLiAK+qbMFYIZc5iKXSXitgx5Ijmu6cejqPIT29DumqrvMUkqGRstRPqFWFYniNEnDnOKwKWYK9NDK9vMzawLWPGUa8jgHG7t/LSBQ1MZiduglW/2YKMPiQ6Lj207Sb3maNggNezIqdWrmJc/oVD2tzuKMBj/1WxLACQzm/gCFmp9upCgA17bhju9aAVJUG9itcaNIRbiTiydXVZDupO9A+rGTNXRxzL8Ju4OVznGK0F/yxFzQ9ETZqyJIwflu8dOwcfQw1ZU8ZehYt8779YqCqpVij+vBSyQsnTI9Pts78XMBuJiw7KI+wMyOX2z+yDWzHPqISvFUmTQtLktpBOeySeh13LaE9Q6uJ6cgd6h5X60d0mNY9eUjdJfbtiRnUtZvxns4bHPs6CxgY6j+0xlybASgAg9Xm8CtPjHV+pmf6Q/QqwvbuoAPCUDXJ6ke65UROBK3dXMrD+4TGN1oe6SI+uek7hR5Z+iojmxvV+HMySrFtRJLMpyMoRp26iwR/ovZU7BTtng4pC6hhac0QLp4ItLN0wDqOZbZcELc/mEdfxlS6lByfaYeYzfSQRMXaEvpRTWl6LznLzRVA4GEGALAXpTIs9f5If+Bg==
  template:
    metadata:
      annotations: *a1
      name: app-env
    type: Opaque

