name: Production

on:
  push:
    tags:
      - v*

concurrency:
  group: production
  cancel-in-progress: true

jobs:

  deploy:
    name: Deploy production
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://archifiltre-statistics.fabrique.social.gouv.fr/
    steps:

    - name: Use autodevops to deploy production
      uses: SocialGouv/actions/autodevops-helm@v1
      with:
        environment: prod
        token: ${{ secrets.GITHUB_TOKEN }}
        imageName: archifiltre/${{ env.project }}
        kubeconfig: ${{ secrets.SOCIALGOUV_KUBE_CONFIG_PROD }}
        rancherId: ${{ secrets.RANCHER_PROJECT_ID }}
        socialgouvBaseDomain: ${{ secrets.SOCIALGOUV_BASE_DOMAIN }}
