name: Review

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - v*

concurrency:
  cancel-in-progress: true
  group: review-${{ github.ref }}

jobs:

  deploy:
    name: Deploy review branch
    runs-on: ubuntu-latest
    steps:
    - name: Use autodevops to deploy review branch
      uses: SocialGouv/actions/autodevops-helm@v1
      with:
        environment: dev
        token: ${{ secrets.GITHUB_TOKEN }}
        imageName: archifiltre/archifiltre-statistics
        kubeconfig: ${{ secrets.SOCIALGOUV_KUBE_CONFIG_DEV }}
        rancherId: ${{ secrets.RANCHER_PROJECT_ID }}
        socialgouvBaseDomain: ${{ secrets.SOCIALGOUV_BASE_DOMAIN }}
